FROM amd64/ubuntu:18.04

RUN apt-get update && apt-get install groff -y && apt-get install -y wget && apt-get install -y python3 && apt-get -y install python3-pip && rm -rf /var/lib/apt/lists/*
RUN pip3 install awscli --upgrade
RUN aws --version